### ISSUE TITLE
Error with Redux DevTools - Can't replay actions

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/fable-elmish#31]
I tried the counter sample with the `Redux DevTools`. Everything works fine but when I try to reverse or replay actions, I get the error below in the console

````
Unable to process monitor command Object {type: "DISPATCH", payload: Object, state: "2", id: "1", source: "@devtools-extension"} Error: Cannot resolve generic argument a: TypeError: Cannot read property 'generics' of undefined
    at resolveGeneric (http://localhost:8080/bundle.js:24552:15)
    at inflate (http://localhost:8080/bundle.js:24913:127)
    at inflatePublic (http://localhost:8080/bundle.js:24984:12)
    at http://localhost:8080/bundle.js:25928:145
    at <anonymous>:1:23668
    at <anonymous>:1:20331
    at Array.forEach (native)
    at <anonymous>:1:20311
    at Array.forEach (native)
    at handleMessages (<anonymous>:1:20237)
(anonymous) @ debugger.js:127
(anonymous) @ VM1007:1
(anonymous) @ VM1007:1
(anonymous) @ VM1007:1
handleMessages @ VM1007:1
````

I'm getting similar errors with the other samples.

Part of the code for the sample is as below

````
module Counter =
  type Msg =
    | Increment
    | Decrement
  
  type Model = int
  let init () = 0
  let update msg count =
    match msg with
    | Increment -> count + 1
    | Decrement -> count - 1
  
  open Fable.Helpers.React
  open Fable.Helpers.React.Props

  let view (model:int) dispatch =
    div []
      [ button 
          [ OnClick <| fun _ -> dispatch Decrement ] 
          [ str "-" ]
        span [] [ str <| string model ]
        button 
          [ OnClick <| fun _ -> dispatch Increment ]
          [ str "+" ] ]


open Elmish.React
open Elmish.Debug

let run =
    Program.withConsoleTrace
    >> Program.withReact "main"
    >> Program.withDebugger
    >> Program.run

let counter () = Program.mkSimple Counter.init Counter.update Counter.view

counter () |> run
````

Screen cast [here](http://recordit.co/5mduUJbLES)
What am I missing?

**Comment by rkosafo** [comment]
I have it working for a sample with the model as defined below.
Could it be because I'm using an object here while a primitive in the other one?

    type Model =
        { inputs: float list
          answer: float }

**Comment by et1975** [comment]
It probably happens as the count hits 0, as you guessed redux tools expects an object but we are passing a primitive, at 0 it doesn't survive the roundtrip. It's a known shortcoming, and i didn't bother fixing it any real model will be an object.
